name: 'Build'

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '15 10 */3 * *'

jobs:

  build:
    name: 'Build'
    runs-on: 'ubuntu-20.04'
    env:
      PLAYWRIGHT_BROWSERS_PATH: '0'
    steps:
      - name: 'Checkout project'
        uses: 'actions/checkout@v2'
      - name: 'Cache node modules'
        uses: 'actions/cache@v2'
        with:
          path: '~/.npm/'
          key: "${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}"
          restore-keys: '${{runner.os}}-node-'
      - name: 'Install dependencies'
        run: |
          npm install
      - name: 'Lint'
        run: |
          npm run lint
      - name: 'Build'
        run: |
          npm run build
      - name: 'Test (node)'
        run: |
          node --version
          npm run test:node
      - name: 'Test (deno)'
        run: |
          export DENO_INSTALL="$HOME/.deno"; export PATH="$DENO_INSTALL/bin:$PATH"
          curl -fsSL --proto '=https' --tlsv1.3 'https://deno.land/x/install/install.sh' | sh
          deno --version
          npm run test:deno
      - name: 'Test (browser)'
        run: |
          "$(node -e 'process.stdout.write(require("playwright").chromium.executablePath());')" --version
          "$(node -e 'process.stdout.write(require("playwright").firefox.executablePath());')" --version
          npm run test:browser
      - name: 'Docs'
        run: |
          npm run docs
